CORTX-30464: Add DPS features into PerfLine
Seagate/seagate-tools pull request #562
Opened 2022-07-12 14:34 UTC by maximalezhin

## Problem Statement

This patch combines multiple DPS-related features that extend debugging capabilities of PerfLine:
- Single-script installation for K8s environment
- Interactive debugging sessions
- OS version detection (Rocky Linux / CentOS) during installation

Signed-off-by: Maxim Malezhin <maxim.malezhin@seagate.com>

## Design

-  Interactive script `/performance/PerfLine/env/install_dev_env.sh` allows to deploy K8s CORTX cluster and PerfLine utility by executing only a single script
- Interactive debugging feature for extended 

> **Following are the checklists for the author. Make sure all the items are considered. Write NA in front if any point is not applicable.**

## Coding

-   [+] Coding conventions are followed and code is consistent
-   [ ] No new Codacy Issues are added
-   [+] Version is updated in the respective VERSION file, format - `<tool>_v<major>.<minor>.<patch>`

## Documentation

-   [ ] Changes done to readme file / Quick Start Guide
-   [ ] Docstrings are added to new functions/ files with Summary, Args and Return params

## Testing

-   [+] New/Affected tests are executed on Latest Build
-   [ ] Attach test execution logs
-   [+] No regression introduced

## Pull Request

-   [+] JIRA number/GitHub Issue added to PR, format - `<ID>: <Title>`
-   [+] Only one commit is present, format -
    ```txt
    <ID>: <Commit message>
    - bullets of changes committed in the PR
    ```
-   [+] Commit is sign-offed

## Review Checklist

-   [+] PR is self reviewed
-   [+] JIRA ticket state/status is updated
-   [+] Check if the DoD, description is clear and explained

## Impact Analysis

  (Checklist for Author/Reviewer/GateKeeper)

-   [+] Are there any changes in any common function?

  If yes,

-   [+] Relative/ dependent function calls are updated
-   [+] Executed all affected tests

> Note: If checkboxes are not working, write Y/N in front of the bullets. Thanks for your contribution and Happy Coding!

2022-07-12 15:57 UTC, rahul27kumar requested changes
Could please add readme files for dps? It would be also help for reviewer to review because it is a newly added feature for a perfline.

2022-07-13 14:44 UTC, maximalezhin commented on performance/PerfLine/env/install_dev_env.sh
> +PERFLINE_DEFAULT_BRANCH="dps"
Done.

2022-07-13 14:44 UTC, maximalezhin commented on performance/PerfLine/env/solution.yaml
> +solution:
Done.

2022-07-13 14:44 UTC, maximalezhin commented
Requesting the next round of review. @rahul27kumar

2022-07-13 16:23 UTC, rahul27kumar requested changes
@maximalezhin  Please rename your readme.md file to README.md. your readme.md file helps me to review your PR. But still few features that you added as a part of this PR which is not mention anywhere in README.md file. Could you please have a look at my comment? And add usage/steps for continue_task, wait_task and common_wait.

2022-07-13 16:23 UTC, rahul27kumar commented on performance/PerfLine/roles/perfline_setup/files/wrapper/continue_task.sh
> +#!/usr/bin/env bash
Could you please add the usage of this functionality/feature on PerfLine README.md file? I didn't find any description/details about it.

2022-07-13 16:23 UTC, rahul27kumar commented on performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/common_wait.sh
> +#!/usr/bin/env bash
same here. Add some steps and usage of this feature on README.md file of PerfLine.

2022-07-13 16:23 UTC, rahul27kumar commented on performance/PerfLine/roles/perfline_setup/files/wrapper/wait_task.sh
> +#!/usr/bin/env bash
if this is also a part of new feature then please mention it on PerfLine README.md file.

2022-07-14 13:25 UTC, maximalezhin commented on performance/PerfLine/env/install_dev_env.sh
> +    sed -i 's:^disk=.*:disk="/dev/sdb":g' "$PERFLINE_HOSTS_FILENAME"
Agree

2022-07-15 12:44 UTC, sampadap03 approved these changes

2022-07-15 12:46 UTC, rahul27kumar approved these changes
Approved

2022-07-18 04:44 UTC, sampadap03 commented
Alex workflow issues are fixed. Mention of `host` is part of ansible design hence bypassing.

2022-07-18 04:44 UTC, merged