CORTX-33500: [SuperPerf][Perf-Rest] Support for baseline wrt infra type
Seagate/seagate-tools pull request #565
Opened 2022-07-18 14:27 UTC by sampadap03

## Problem Statement

Need to add a feature for providing baseline on VM and HW infrastructure for Performance Sanity.

Signed-off-by: Sampada Petkar <sampada.petkar@seagate.com>

## Design

- The "CUSTOM" field is passed from Jenkins as the "infrastructure" from build parameters.
- Stored in sanity_config of performance_db as "Custom_Label.
- In Perf-Rest, queried for request run_id custom_label and identified baseline of that infra type.

## Coding

-   [x] Coding conventions are followed and code is consistent
-   [x] No new Codacy Issues are added
-   [x] Version is updated in the respective VERSION file - SuperPerf v0.2.0

## Documentation

-   [x] Changes done to readme file / Quick Start Guide
-   [x] Docstrings are added to new functions/ files with Summary, Args and Return params

## Testing

-   [x] New/Affected tests are executed on Latest Build
-   [x] Attach test execution logs
-   [x] No regression introduced

## Pull Request

-   [x] JIRA number/GitHub Issue added to PR
-   [x] Only one commit is present
-   [x] Commit is sign-offed

## Review Checklist

-   [x] PR is self reviewed
-   [x] JIRA ticket state/status is updated
-   [x] Check if the DoD, description is clear and explained

## Impact Analysis

  (Checklist for Author/Reviewer/GateKeeper)

-   [x] Are there any changes in any common function?

  If yes,

-   [x] Relative/ dependent function calls are updated
-   [x] Executed all affected tests

> Note: If checkboxes are not working, write Y/N in front of the bullets. Thanks for your contribution and Happy Coding!

-----
[View rendered performance/PerfPro/readme.md](https://github.com/sampadap03/seagate-tools/blob/CORTX-33500/performance/PerfPro/readme.md)

2022-07-19 04:45 UTC, rahulr-seagate approved these changes

2022-07-19 06:41 UTC, rahul27kumar requested changes
Please have a look at my comment.

2022-07-19 06:41 UTC, rahul27kumar commented on dashboards/perf-rest/rest_app/sanityapi.py
>      else:
"else" part is not required here... you can directly `return "VM"`.
This would set to default "VM" and other sides we already have a condition for "HW" and that's enough for us.

2022-07-21 04:59 UTC, sampadap03 commented on dashboards/perf-rest/rest_app/sanityapi.py
>      else:
sure

2022-07-21 05:29 UTC, sampadap03 commented on dashboards/perf-rest/rest_app/sanityapi.py
>      else:
added in [3d2a134](https://github.com/Seagate/seagate-tools/pull/565/commits/3d2a134df0e0c8940adeea7d22637a805b1b8dae)

2022-07-21 05:33 UTC, rajeshdesh approved these changes
LGTM!

2022-07-21 05:41 UTC, rahul27kumar approved these changes

2022-07-21 05:53 UTC, sampadap03 commented
For http://127.0.0.1:5050/sanity/throughput?run_id=62cfbd465b702f09d15b94bf:

> {
    "result": {
        "read": {
            "baseline": {
                "128MB": 460.875,
                "16MB": 493.062,
                "256KB": 36.34
            },
            "deviation": {
                "128MB": 0.0,
                "16MB": 0.0,
                "256KB": 0.0
            },
            "difference": {
                "128MB": 0.0,
                "16MB": 0.0,
                "256KB": 0.0
            },
            "value": {
                "128MB": 460.875,
                "16MB": 493.062,
                "256KB": 36.34
            }
        },
        "write": {
            "baseline": {
                "128MB": 451.916,
                "16MB": 370.48,
                "256KB": 35.766
            },
            "deviation": {
                "128MB": 0.0,
                "16MB": 0.0,
                "256KB": 0.0
            },
            "difference": {
                "128MB": 0.0,
                "16MB": 0.0,
                "256KB": 0.0
            },
            "value": {
                "128MB": 451.916,
                "16MB": 370.48,
                "256KB": 35.766
            }
        }
    }
}

Tested with VM/ HW baseline data

2022-07-21 05:57 UTC, merged