CORTX-30462: Added support for m0crate KV workload in PerfLine
Seagate/seagate-tools pull request #575
Opened 2022-07-25 14:59 UTC by rahul27kumar

Signed-off-by: Rahul Kumar <rahul.kumar@seagate.com>

## Problem Statement

DPS team has requested KV workload m0crate support in PerfLine utility. PerfLine shall support execution of IO and KV workloads as a part of built-in workload execution.

## Design

-   New m0crate-kv workload features has been added as a part of perfline workload.

> **Following are the checklists for the author. Make sure all the items are considered. Write NA in front if any point is not applicable.**

## Coding

-   [x] Coding conventions are followed and code is consistent
-   [x] No new Codacy Issues are added
-   [x] Version is updated in the respective VERSION file, format - `<tool>_v<major>.<minor>.<patch>`

## Documentation

-   [ ] Changes done to readme file / Quick Start Guide
-   [ ] Docstrings are added to new functions/ files with Summary, Args and Return params

## Testing

-   [x] New/Affected tests are executed on Latest Build
-   [x] Attach test execution logs 
-   [ ] No regression introduced

## Pull Request

-   [x] JIRA number/GitHub Issue added to PR, format - `<ID>: <Title>`
-   [x] Only one commit is present, format -
    ```txt
    commit 1d5e503f21a29c3a91bbde5def36572b4a34c405
    Author: Rahul Kumar <rahul.kumar@seagate.com>
    Date:   Mon Jul 25 07:43:13 2022 -0600

    CORTX-30462: Added support for m0crate KV workload in PerfLine

    Signed-off-by: Rahul Kumar <rahul.kumar@seagate.com>
    ```
-   [x] Commit is sign-offed

## Review Checklist

-   [x] PR is self reviewed
-   [x] JIRA ticket state/status is updated
-   [x] Check if the DoD, description is clear and explained

## Impact Analysis

  (Checklist for Author/Reviewer/GateKeeper)

-   [ ] Are there any changes in any common function?

  If yes,

-   [ ] Relative/ dependent function calls are updated
-   [ ] Executed all affected tests

> Note: If checkboxes are not working, write Y/N in front of the bullets. Thanks for your contribution and Happy Coding!

2022-07-25 15:32 UTC, rajeshdesh approved these changes
Looks good to me

2022-07-27 13:10 UTC, alexsukhachev requested changes
Please look at my messages

2022-07-27 13:10 UTC, alexsukhachev commented on performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/worker.sh
> +                if "io" in "$m0crate_log"
Are you sure that it is a correct construction in bash? For me it looks like some python code :-).
I have tested it so
```
-bash-4.2$ if "io" in "test_io.yaml"; then echo YES; else echo NO; fi;
-bash: io: command not found
NO
-bash-4.2$
```
and realized that it doesn't work. My suggestion is
```
local tmp=$(echo "$m0crate_log" | grep "io") # please use some good name instead of tmp
if [[ -n "$tmp" ]]; then
    # do something
fi
```

2022-07-27 13:10 UTC, alexsukhachev commented on performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/worker.sh
> +        "m0crate" | "m0crate-io")
I would prefer to remove `m0crate` here and have only `m0crate-io`

2022-07-27 13:10 UTC, alexsukhachev commented on performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/worker.sh
> +        --m0crate | --m0crate-io | --m0crate-kv)
the same

2022-07-27 13:10 UTC, alexsukhachev commented on performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/worker.sh
> +        --m0crate-params | --m0crate-io-params)
the same. In my opinion it would be better to remove old option `--m0crate-params`

2022-07-27 13:10 UTC, alexsukhachev commented on performance/PerfLine/roles/perfline_setup/files/wrapper/stat/report_generator/gen_report.py
> +            if "io" in m0crate_logs:
it will not work. `m0crate_logs` is a list of filenames. Such code
```
if 'io' in m0crate_logs:
    print('something')
```
will not call `print()` function because there is no 'io' filename in the list ['m0crate_io.log', 'm0crate_io_2.log'].
Correct code is
```
for f in m0crate_logs:
    if 'io' in f:
        m0crate_log_path = join(dir_path, f)
        m0crate_rw_stats[f] = m0crate_log_parser.parse_m0crate_log(m0crate_log_path)
```

2022-07-27 13:45 UTC, rahul27kumar commented on performance/PerfLine/roles/perfline_setup/files/wrapper/core/tasks.py
> +            options.append(params_str)
It just because to support backward compatibilities too.
There is no such difference between m0crate and m0crate_io.
I already discussed with @maximalezhin about backward compatibilities.

2022-07-27 13:49 UTC, rahul27kumar commented on performance/PerfLine/roles/perfline_setup/files/wrapper/core/validator.py
> +                                }
Hope ! Above comment justify then duplication. @alexsukhachev

2022-07-27 14:01 UTC, rahul27kumar commented on performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/worker.sh
> +                if "io" in "$m0crate_log"
oh ! good catch

I think below one would be the best way:
`# if grep -q "io" <<< "test_io.yaml"; then echo "YES"; else echo "NO"; fi;
YES
#
`

2022-07-27 14:46 UTC, rahul27kumar commented on performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/worker.sh
> +        --m0crate | --m0crate-io | --m0crate-kv)
removed "--m0crate |"

2022-07-27 14:46 UTC, rahul27kumar commented on performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/worker.sh
> +        --m0crate-params | --m0crate-io-params)
considered only "--m0crate-io-params"

2022-07-27 14:47 UTC, rahul27kumar commented on performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/worker.sh
> +        "m0crate" | "m0crate-io")
we have considered only "m0crate-io"

2022-07-28 14:50 UTC, alexsukhachev approved these changes
approved

2022-07-29 07:29 UTC, sampadap03 approved these changes

2022-07-29 07:29 UTC, merged