CORTX-33075: [Perf-Sanity] Fix /all not displaying data on fresh load
Seagate/seagate-tools pull request #582
Opened 2022-08-04 17:05 UTC by sampadap03

## Problem Statement
The high Concurrency table is not showing data on a fresh load. Throws no IndexError: no such item for cursor instance.
side fix: rounded off difference row for the same table

Signed-off-by: Sampada Petkar <sampada.petkar@seagate.com>

## Design

Accessed run_id from converted JSON from API response

## Coding

-   [ ] Coding conventions are followed and code is consistent
-   [ ] No new Codacy Issues are added
-   [ ] Version is updated in the respective VERSION file

## Documentation

-   [ ] Changes done to readme file / Quick Start Guide
-   [ ] Docstrings are added to new functions/ files with Summary, Args and Return params

## Testing

-   [ ] New/Affected tests are executed on Latest Build
-   [ ] Attach test execution logs
-   [ ] No regression introduced

## Pull Request

-   [ ] JIRA number/GitHub Issue added to PR, format - `<ID>: <Title>`
-   [ ] Only one commit is present

## Review Checklist

-   [ ] PR is self reviewed
-   [ ] JIRA ticket state/status is updated
-   [ ] Check if the DoD, description is clear and explained

## Impact Analysis

  (Checklist for Author/Reviewer/GateKeeper)

-   [ ] Are there any changes in any common function?

  If yes,

-   [ ] Relative/ dependent function calls are updated
-   [ ] Executed all affected tests

> Note: If checkboxes are not working, write Y/N in front of the bullets. Thanks for your contribution and Happy Coding!

2022-08-04 17:07 UTC, sampadap03 commented
Tested on Production - http://cftic2.pun.seagate.com:3030/?run_id=62bd7717ac1fc37281a24220
![image](https://user-images.githubusercontent.com/40736070/182909771-8c91ed43-aa17-4cd0-9827-ad149066affa.png)

2022-08-05 04:22 UTC, rajeshdesh approved these changes

2022-08-10 08:03 UTC, rahul27kumar requested changes
Please have a look at my comments

2022-08-10 08:03 UTC, rahul27kumar commented on dashboards/perf-rest/setup.py
> +setup(name='Perf-Rest', version='0.2.2', packages=find_packages())
Please increment it by +1 only.

2022-08-10 08:03 UTC, rahul27kumar commented on dashboards/superperf/VERSION
> +VERSION superperf_v0.2.2
same here

2022-08-12 13:01 UTC, rahul27kumar approved these changes

2022-08-12 13:02 UTC, merged