CORTX-22807: Fix issues for iostat, dstat and blktrace collections
Seagate/seagate-tools pull request #585
Opened 2022-09-02 14:41 UTC by rahul27kumar

Signed-off-by: Rahul Kumar <rahul.kumar@seagate.com>

## Problem Statement

Their is an issues while stats collection for iostat, dstat and blktrace. Fixes some minor issues for respective source code.

## Design

-   stats collections were not collecting properly for iostat, dstat and blktrace. 

> **Following are the checklists for the author. Make sure all the items are considered. Write NA in front if any point is not applicable.**

## Coding

-   [x] Coding conventions are followed and code is consistent
-   [x] No new Codacy Issues are added
-   [ ] Version is updated in the respective VERSION file, format - `<tool>_v<major>.<minor>.<patch>`

## Documentation

-   [ ] Changes done to readme file / Quick Start Guide
-   [ ] Docstrings are added to new functions/ files with Summary, Args and Return params

## Testing

-   [x] New/Affected tests are executed on Latest Build
-   [ ] Attach test execution logs
-   [x] No regression introduced

## Pull Request

-   [x] JIRA number/GitHub Issue added to PR, format - `<ID>: <Title>`
-   [x] Only one commit is present, format -
    ```txt
    commit 43e060bb2a12ddf8f9f944356b8c19a7512a5442
    Author: Rahul Kumar <rahul.kumar@seagate.com>
    Date:   Fri Sep 2 08:23:02 2022 -0600

    CORTX-22807: Fix issues for iostat, dstat and blktrace collections

    Signed-off-by: Rahul Kumar <rahul.kumar@seagate.com>

    ```
-   [x] Commit is sign-offed

## Review Checklist

-   [x] PR is self reviewed
-   [x] JIRA ticket state/status is updated
-   [x] Check if the DoD, description is clear and explained

## Impact Analysis

  (Checklist for Author/Reviewer/GateKeeper)

-   [ ] Are there any changes in any common function?

  If yes,

-   [ ] Relative/ dependent function calls are updated
-   [x] Executed all affected tests

> Note: If checkboxes are not working, write Y/N in front of the bullets. Thanks for your contribution and Happy Coding!

2022-09-06 04:07 UTC, rahul27kumar commented
[workload.log](https://github.com/Seagate/seagate-tools/files/9493192/workload.log)
Logs for successful execution of perfline for iostats
Results for iostats collection on http://ssc-vm-g3-rhev4-3136.colo.seagate.com:8005/report/b232c41a-f8ee-4b43-930b-56b5df2fb1fe

2022-09-06 06:11 UTC, rkothiya commented on performance/PerfLine/roles/perfline_setup/files/wrapper/stat/stop_stats_service.sh
> +               --disks ${disks_dm} \
Please give double quote to this

2022-09-06 06:12 UTC, rkothiya commented on performance/PerfLine/roles/perfline_setup/files/wrapper/stat/stop_stats_service.sh
> +     iowatcher ${dumps} -o node."$(hostname -s)".aggregated.svg
Please give double quote to dumps.

2022-09-06 06:12 UTC, rkothiya commented on performance/PerfLine/roles/perfline_setup/files/wrapper/stat/stop_stats_service.sh
> +         iowatcher ${dumps} -o node."$(hostname -s)".${graph}.svg -O ${graph}
Please give double quote to dumps

2022-09-06 08:16 UTC, sampadap03 requested changes
small change please do

2022-09-06 08:16 UTC, sampadap03 commented on performance/PerfLine/VERSION
> +
remove an extra line from here

2022-09-06 08:23 UTC, rahul27kumar commented on performance/PerfLine/roles/perfline_setup/files/wrapper/stat/stop_stats_service.sh
> +               --disks ${disks_dm} \
This command will fail if we use "${disks_dm}". The commands will expect for a list of disk not a string type value.
Double quotes convert it  to string. So, We should ignore codacy issues related to this file.

2022-09-06 08:24 UTC, rahul27kumar commented on performance/PerfLine/roles/perfline_setup/files/wrapper/stat/stop_stats_service.sh
> +     iowatcher ${dumps} -o node."$(hostname -s)".aggregated.svg
This command will fail if we use "${dumps}". The commands will expect for a list of disk not a string type value.
Double quotes convert it to string. So, We should ignore codacy issues related to this file.

2022-09-06 08:24 UTC, rahul27kumar commented on performance/PerfLine/roles/perfline_setup/files/wrapper/stat/stop_stats_service.sh
> +         iowatcher ${dumps} -o node."$(hostname -s)".${graph}.svg -O ${graph}
same as above comment

2022-09-06 08:47 UTC, rahul27kumar commented
Successful Tested Perfline execution: http://ssc-vm-g3-rhev4-3136.colo.seagate.com:8005/report/e7f189be-fdde-4437-901d-6caf95bc3e0a

2022-09-06 09:07 UTC, rkothiya approved these changes
LGTM

2022-09-06 10:40 UTC, sampadap03 approved these changes

2022-09-07 03:51 UTC, sampadap03 commented
merging by bypassing codacy checks with the above reasons

2022-09-07 03:52 UTC, merged