CORTX-22793: Update method for s3accound creation
Seagate/seagate-tools pull request #586
Opened 2022-09-05 11:57 UTC by rkothiya

Signed-off-by: Rinku Kothiya <rinku.kothiya@seagate.com>

## Problem Statement

Update method for s3accound creation

## Design

-   For Bug, Describe the fix here.
-   For Feature, Post the link for design.

> **Following are the checklists for the author. Make sure all the items are considered. Write NA in front if any point is not applicable.**

## Coding

-   [ ] Coding conventions are followed and code is consistent
-   [ ] No new Codacy Issues are added
-   [ ] Version is updated in the respective VERSION file, format - `<tool>_v<major>.<minor>.<patch>`

## Documentation

-   [ ] Changes done to readme file / Quick Start Guide
-   [ ] Docstrings are added to new functions/ files with Summary, Args and Return params

## Testing

-   [ ] New/Affected tests are executed on Latest Build
-   [ ] Attach test execution logs
-   [ ] No regression introduced

## Pull Request

-   [ ] JIRA number/GitHub Issue added to PR, format - `<ID>: <Title>`
-   [ ] Only one commit is present, format -
    ```txt
    <ID>: <Commit message>
    - bullets of changes committed in the PR
    ```
-   [ ] Commit is sign-offed

## Review Checklist

-   [ ] PR is self reviewed
-   [ ] JIRA ticket state/status is updated
-   [ ] Check if the DoD, description is clear and explained

## Impact Analysis

  (Checklist for Author/Reviewer/GateKeeper)

-   [ ] Are there any changes in any common function?

  If yes,

-   [ ] Relative/ dependent function calls are updated
-   [ ] Executed all affected tests

> Note: If checkboxes are not working, write Y/N in front of the bullets. Thanks for your contribution and Happy Coding!

2022-09-08 09:19 UTC, rahul27kumar requested changes
Please find my comments

2022-09-08 09:19 UTC, rahul27kumar commented on performance/PerfLine/roles/perfline_setup/files/s3account/lc_setup_aws.sh
> +if [ $1 == "rgw" ]
Please resolve this codacy error

2022-09-08 09:19 UTC, rahul27kumar commented on performance/PerfLine/roles/perfline_setup/files/s3account/lc_setup_aws.sh
Please add license to this file

2022-09-08 09:19 UTC, rahul27kumar commented on performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/LC/s3srv_artifacts.sh
> +    #ssh "$PRIMARY_NODE" "$SCRIPT_DIR/../../s3account/lc_create_user.sh"
Remove this comment line

2022-09-08 09:26 UTC, rkothiya commented on performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/LC/s3srv_artifacts.sh
> +    #ssh "$PRIMARY_NODE" "$SCRIPT_DIR/../../s3account/lc_create_user.sh"
done

2022-09-08 09:33 UTC, rahul27kumar commented on performance/PerfLine/roles/perfline_setup/files/s3account/lc_setup_aws.sh
No, not required any action regarding license. I thought You had created a new script.

2022-09-08 10:18 UTC, rahul27kumar requested changes
minor modifications required

2022-09-08 10:18 UTC, rahul27kumar commented on performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/LC/rgw_artifacts.sh
> +    ssh "$PRIMARY_NODE" "$SCRIPT_DIR/../../s3account/lc_setup_aws.sh rgw"
instead of using `rgw` I would recommend to make use of "S3_APP" variable which is defined in perfline.conf. No need to source that file, you can directly use this variables. Same will also work for [s3srv_artifacts.sh](https://github.com/Seagate/seagate-tools/pull/586/files#diff-2f5e005cebe1efef41c8ca93ba0bb6d16b6b90637fcc436561d25b79bc5dd317)

2022-09-08 12:05 UTC, rkothiya commented on performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/LC/rgw_artifacts.sh
> +    ssh "$PRIMARY_NODE" "$SCRIPT_DIR/../../s3account/lc_setup_aws.sh rgw"
done

2022-09-08 12:27 UTC, rahul27kumar approved these changes
Approved

2022-09-09 04:05 UTC, sampadap03 approved these changes

2022-09-09 04:54 UTC, merged